### ISSUE TITLE
Code Sample OverFlow in Mobile View

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#13]
## Overflow of code sample

![image](https://user-images.githubusercontent.com/53480076/92638903-ad358b00-f2f8-11ea-90b3-c46ba6c83472.png)

## Solution
adding `overflow: scroll;` to code class in custom css

**Comment by imabp** [comment]
@tarunnsingh Issue solved in the ongoing pull request #12 
### Steps Taken
in `src/index.css` set `overflow` to `scroll`

#Final View
![Scroll](https://user-images.githubusercontent.com/53480076/92639551-97749580-f2f9-11ea-8d72-ea6bf2923bdd.gif)

**Comment by tarunnsingh** [comment]
Closing since it's done now.
