### ISSUE TITLE
Links in sidebar not styled

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#14]
**The links in the sidebar are not styled as hyperlinks.**
- Should be blue in color.
- Cursor should change on hover.

**_See this SS._**
![image](https://user-images.githubusercontent.com/31896659/92717177-6ccc2080-f37d-11ea-8c92-dfa39233d802.png)

**Comment by priyanshu0405** [comment]
Hey @tarunnsingh, can I take this issue? Thanks!!

**Comment by tarunnsingh** [comment]
Yes Sure @priyanshu0405 go ahead.
