### ISSUE TITLE
Header Redesign - Material UI 

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#20]
The Current header design needs a **Fresher Look**. Come up with your creativity and be a part of the Alexa Community Jaipur Developers.

_Before asking for assigning the issue, make sure you are able to run the project locally. If you face any errors, comment down._ 😄

**Comment by EnechukwuChibuike** [comment]
Can I do that?

**Comment by tarunnsingh** [comment]
Sure, were you able to run the project locally without any errors?

**Comment by harshalkaigaonkar** [comment]
is it open?

**Comment by tarunnsingh** [comment]
Yes @harshalkaigaonkar it is open. Would you like to work?

**Comment by harshalkaigaonkar** [comment]
@tarunnsingh yes!!

**Comment by harshalkaigaonkar** [comment]
I want to ask that is there more buttons or functions do we need on the header?

**Comment by tarunnsingh** [comment]
We would need a Drop Down button for Blogs and a Logout button only as of now. 
Thanks!

**Comment by harshalkaigaonkar** [comment]
Yeah okay!

**Comment by tarunnsingh** [comment]
If you want to add more functions, you are always welcome.
Or if not now then later on I'd put more issue on any such requirements and assign them to you.
As making a successfull PR on this issue, you'd be a part of contributors.

**Comment by harshalkaigaonkar** [comment]
is the Login State is created?

**Comment by harshalkaigaonkar** [comment]
And What about the blog section?

**Comment by tarunnsingh** [comment]
> is the Login State is created?

We are working on Login, but it's not yet implemented.

**Comment by tarunnsingh** [comment]
> And What about the blog section?
> 

The current pages displays blogs on the first page itself, in future we'd separate this into different pages, for that we would require a blogs drop-down, the drop down menu would contain the different categories of blogs. As of now if a dummy implementation of the same (the drop-down) is required

**Comment by harshalkaigaonkar** [comment]
just check the PR . And respond.

**Comment by harshalkaigaonkar** [comment]
whats the issue with the PR?

**Comment by tarunnsingh** [comment]
Sorry for late response, I'll review your PR in a while.

**Comment by tarunnsingh** [comment]
Closing since Done.
