### ISSUE TITLE
Adding Concurrent dev run Feature

### ISSUE THREAD

**Issue by dkapur17** [alexa-dev-hub/alexa-community-jaipur#23]
Currently, to run the app in dev you need to perform the following sequence of commands:

```
npm run dev
cd client
npm run start
```

This can be reduced to a single command using the `concurrently` package. Its a minor change, but makes workflow all that simpler.

Would like to add this feature.

**Comment by tarunnsingh** [comment]
That would be great, was going to put up this issue.

**Comment by dkapur17** [comment]
@tarunnsingh made the required PR (#24)

**Comment by tarunnsingh** [comment]
Great thanks! @dkapur17
