### ISSUE TITLE
Improve the Docs.

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#3]
Modify the README with proper Syntax and Emojis.
Make sure you do not delete any content.

**Comment by sumanthst24** [comment]
What syntax do we need to change in readme file?

**Comment by tarunnsingh** [comment]
Nothing particular for the Syntax, but if you could add some helpful links (React-Docs etc.) an Index, some good illustrations, badges and more. 
Sole purpose of this issue is for beginners to start contributing to open source in any manner.

**Comment by sumanthst24** [comment]
I'll work on it if assigned

**Comment by sumanthst24** [comment]
Can I also include the stats for the repo like number of pull requests and issues ?

**Comment by tarunnsingh** [comment]
Ye Sure, that would be great!

**Comment by sumanthst24** [comment]
https://github.com/alexa-dev-hub/alexa-community-jaipur/pull/9
Created pull request to this issue

**Comment by tarunnsingh** [comment]
#9 
I am closing the issue now, good work @sumanthst24

**Comment by sumanthst24** [comment]
Thank you @tarunnsingh
