### ISSUE TITLE
Deployment to Netlify

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#31]
**Site loading time is slow**
We can avoid this, by deploying it to netlify, and can see deploy previews for each pull request and it will be more helpful for the maintainers to review and see the output of code for each pull request, without worrying about the main production website.

**Comment by tarunnsingh** [comment]
I was thinking of doing so, but the thing is we have shared this website link at many places (*...herokuapp.com*), which would then need to be replaced everywhere. Although we can work on replacing them too.

**Comment by tarunnsingh** [comment]
Can the current Heroku Deployment be altered to respond faster, maybe increasing Dynos. But that again can't be done in Heroku Free tier. 😞

**Comment by imabp** [comment]
@tarunnsingh I have a solution for it, lets do this thing.. 

### Lets create a branch name `v1-deployment` and we will set in heroku that deploy this branch. 
Now in `v1-deployment`, what we will do, we will not load the complete site. Instead we will mention, in the homepage itself, that we have upgraded to V2 website, check here. 
and below that there would be a link

### Next Step
We will update the links on master branch, i.e. wherever we used herokuapp link, we will update it to netlify link and finally deploy `master` to netlify. 😋😋 Hurray !! we didn't break any changes. 

### How is the solution,😅 if good, 🥺do me a favour, follow my open source organization on instagram : https://instagram.com/tech_phantoms and we will have open source sessions if possible a collaboration. 😊😊😊 I hope that sounds fine ? 

### Requested look for V1 branch
![image](https://user-images.githubusercontent.com/53480076/94998299-85bba080-05ce-11eb-8190-80a46a3a3054.png)

**Comment by tarunnsingh** [comment]
**Hey that's absolutely perfect solution to the problem.
Let's do this.**
And sure, would be great to have a collaboration! 😄

**Comment by imabp** [comment]
Thankyou @tarunnsingh  . I am obliged.
Would you like to assign me as member in this org. So that I can directly setup this remote repo, in my local env. 
And work faster ?

**Comment by imabp** [comment]
Checklist  @tarunnsingh , we can follow.
- [x] Create `v1-deployment` branch.
- [x] Deploy `v1-deployment` branch to heroku.
- [x] Deploy `master` branch to netlify.
- [ ] Update `v1-deployment` branch codebase, to above shown image.
- [x] Remove hardcode from `master` as referenced in issue #32
- [ ] All done. Lets work on other issues.

**Comment by tarunnsingh** [comment]
> Thankyou @tarunnsingh . I am obliged.
> Would you like to assign me as member in this org. So that I can directly setup this remote repo, in my local env.
> And work faster ?

Sure sending you the invite.

**Comment by imabp** [comment]
@tarunnsingh 
You can refer this to setup build environment variables in Netlify
https://docs.netlify.com/configure-builds/environment-variables/

**Comment by imabp** [comment]
there has to follow particular setup for builds.. so be careful while setting up that

**Comment by tarunnsingh** [comment]
Hey do we need to deploy client and server separately to Netlify?

**Comment by imabp** [comment]
on Netlify we can deploy the whole client.
on heroku, we are deploying the backend.

We need to do api calling through the herokuapp link.

**Comment by imabp** [comment]
@tarunnsingh netlify is super amazing for client side.

**Comment by imabp** [comment]
@tarunnsingh though I accepted the invite, but still I dont have write access to any repository. 🙁

**Comment by imabp** [comment]
@tarunnsingh I have deployed my fork to netlify, see here : https://alexajaipurforked.netlify.app/

![image](https://user-images.githubusercontent.com/53480076/95008467-c13e8500-0637-11eb-8165-3083cae9efa6.png)

**Comment by imabp** [comment]
@tarunnsingh I was thinking to host the backend at heroku, and use it as core backend only.
And on netlify will be our front end .

Why? 
In heroku, everytime, we send the request, heroku also has to render frontend, this makes it slower, because, it has to handle both the activities, backend+ frontend. 
Decoupling frontend and backend will help to achieve things easily.

**Comment by imabp** [comment]
@tarunnsingh Heroku also setup using CORS API
You can check my forked version of site here: https://alexajaipurforked.netlify.app/

In this above site, I am using alexadevhub heroku api for fetching blog posts

Sending you PR to the master branch.

**Comment by imabp** [comment]
@tarunnsingh Tell me when you publish this repo to netlify. 
I will send PR for `v1-deployment` then only with requested changes shown below
![94998299-85bba080-05ce-11eb-8190-80a46a3a3054](https://user-images.githubusercontent.com/53480076/95011312-5b5cf800-064d-11eb-99b7-68aa42c36254.png)

**Comment by tarunnsingh** [comment]
> @tarunnsingh Heroku also setup using CORS API
> You can check my forked version of site here: https://alexajaipurforked.netlify.app/
> 
> In this above site, I am using alexadevhub heroku api for fetching blog posts
> 
> Sending you PR to the master branch.

Sorry for this late response.
Looks like you've done the whole setup!
Great Merging your PR.

**Comment by imabp** [comment]
@tarunnsingh when are you deploying master to netlify ?

**Comment by imabp** [comment]
I dont have owner rights, so I cant deploy from this original repo to netlify.
So can you pls @tarunnsingh deploy master to netlify, as everything is setup now?
