### ISSUE TITLE
Remove Hardcode

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#32]
@tarunnsingh I saw the core codebase.

**I found out that links are hardcoded.**

Lets make a links.jsx module file and put all the links there with appropriate link names and export it.

And import it, wherever we want to add links.

This would be better approach, because, if sometime later, any links or any link to social account is changed, we need to just replace it at one place. And changes will be affected everywhere.

**Comment by tarunnsingh** [comment]
Closing since Work is Done. Thank again @imabp
