### ISSUE TITLE
Master Deployment to Netlify

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#35]
`master` is not yet deployed to Netlify from this main repo.
@tarunnsingh 
I suggest to create a netlify for this, with name as alexadevhub and deploy master branch.

Hence our netlify url would be, alexadevhub.netlify.app

Then we need to setup our build commnads in Netlify  by going to settings.

- Base Directory as `client`
- Build directory as `client/build`
- Build command as `npm run build`

**Comment by tarunnsingh** [comment]
alexadevhub.netlify.app ya was doing the same

**Comment by imabp** [comment]
Ohhk ya.

**Comment by tarunnsingh** [comment]
Hey and the Heroku Backend is being used to fetch, I am not able to figuire out how you did it. Could you please explain  a bit. 😄

**Comment by tarunnsingh** [comment]
Would be back on this tomorrow morning

**Comment by imabp** [comment]
Yes sure I am explaining @tarunnsingh 
I saw, the whole backend and frontend is already hosted at Heroku
I deployed the frontend on Netlify, and backend is still there on Heroku.

I observed, you have made routes in backend for fetching posts like `/api/post` , something like that.
So I used fetch command to fetch from the heroku backend.
Now as per React Security thing, I need to use CORS , so I did bit research and found out on heroku there is a way to get that by appending **our hreoku url** to this url `https://cors-anywhere.herokuapp.com/`
Finally after appending, the  fetching url would look like `https://cors-anywhere.herokuapp.com/http://alexadevhub.herokuapp.com`

This is used for fetching the data from the HerokuApp backend.

## Note
If you want to do any changes in backend, then you just need to do change in `v1-deployment` backend folders. 
For front end changes, you have to use `master` for netlify.

**Comment by imabp** [comment]
Here is the pictorial view

Main advantage of this is, you can create, as many front ends as u want in future, and  you can still use the same backend for apis

![image](https://user-images.githubusercontent.com/53480076/95013515-5ce2ec00-065e-11eb-9b2e-e9a9ced05e0e.png)

**Comment by imabp** [comment]
@tarunnsingh are you getting my concept ? 😅 If you have any doubts, do say

**Comment by tarunnsingh** [comment]
Yes absolutely, I got them all. Actually I was reviewing the other PR now made as #43 which dosen't import the **LINKS** file which you created, I'm just looking onto it as it may break things in Header.js.

**Comment by tarunnsingh** [comment]
> Yes sure I am explaining @tarunnsingh
> I saw, the whole backend and frontend is already hosted at Heroku
> I deployed the frontend on Netlify, and backend is still there on Heroku.
> 
> I observed, you have made routes in backend for fetching posts like `/api/post` , something like that.
> So I used fetch command to fetch from the heroku backend.
> Now as per React Security thing, I need to use CORS , so I did bit research and found out on heroku there is a way to get that by appending **our hreoku url** to this url `https://cors-anywhere.herokuapp.com/`
> Finally after appending, the fetching url would look like `https://cors-anywhere.herokuapp.com/http://alexadevhub.herokuapp.com`
> 
> This is used for fetching the data from the HerokuApp backend.
> 
> ## Note
> If you want to do any changes in backend, then you just need to do change in `v1-deployment` backend folders.
> For front end changes, you have to use `master` for netlify.

Actually it was that CORS - Heroku thing, I didn't get at first, but your explanation cleared my doubt. Thanks @imabp !!!

**Comment by tarunnsingh** [comment]
Closing Now since the work is done.

**Comment by imabp** [comment]
Ohh fine ! 😅
