### ISSUE TITLE
Created a Loading GIF/Loader - Alexa Themed.

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#47]
### Or you may come up with your unique designs!

**Comment by beatrizsmerino** [comment]
Please assign it to me

**Comment by LucyBo** [comment]
Hello, Would be glad to contribute.

**Comment by tarunnsingh** [comment]
Hey @beatrizsmerino @LucyBo We can have 2 loaders as we would need them in several places in coming future. So I'm
assigning to both. Revert here if you find any issues.

**Comment by beatrizsmerino** [comment]
Great, I'm going to try to create a gif with the nine icon that appears in the video.
Do you need a.gif file or can you make a loader with html and css?

**Comment by tarunnsingh** [comment]
Its better to have a loader made of HTML CSS, so that we can customise it when putting anywhere.

**Comment by LucyBo** [comment]
I'm glad to hear. @beatrizsmerino can you specify exactly which shape/effect you are going to create? Or what second of the movie does it appear?

**Comment by beatrizsmerino** [comment]
if I give you a link where I am doing tests. And when I have it I'll pass it on to you in files on github.
[https://codepen.io/beatrizsmerino/pen/zYBOGBO?editors=1100](https://codepen.io/beatrizsmerino/pen/zYBOGBO?editors=1100)

**Comment by tarunnsingh** [comment]
@LucyBo are you still working on it, although @beatrizsmerino has provided the content, it would be great to have your content added in too. We would definitely use them in future. 
Please let us know, in case you aren't working on this issue. ✌🏼

**Comment by LucyBo** [comment]
@tarunnsingh I'm working on it.  I just need a little bit more time.

**Comment by tarunnsingh** [comment]
Sure @LucyBo take your time.

**Comment by tarunnsingh** [comment]
Closing since done #56 
And no further constructive updates were made.
