### ISSUE TITLE
Fix Header on Mobile View.

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#51]
On mobile devices, the logo on the header gets hidden. If the Blogs Button is moved within an expandable menu when on smaller screens, the Main Logo will appear fully!

[Screenshot_2020-10-05-13-40-52-774_com.android.chrome.jpg](https://user-images.githubusercontent.com/31896659/95055087-6a58ae80-0710-11eb-87f3-b0ddd2bededc.jpg)

**Comment by tarunnsingh** [comment]
@harshalkaigaonkar ?

**Comment by harshalkaigaonkar** [comment]
> @harshalkaigaonkar ?

yes

**Comment by harshalkaigaonkar** [comment]
Actually do you want github icon and login button in the header too in mobile view?

**Comment by tarunnsingh** [comment]
It's better to also put them in the expandable menu in mobile view.

**Comment by harshalkaigaonkar** [comment]
yeah so we want header to show a toggle button and main logo gif in between?

**Comment by tarunnsingh** [comment]
Yes Exactly

**Comment by tarunnsingh** [comment]
So @harshalkaigaonkar did things work out?

**Comment by harshalkaigaonkar** [comment]
yes actually i am trying to fix the issue

**Comment by harshalkaigaonkar** [comment]
but material Ui is not supporting custom css

**Comment by tarunnsingh** [comment]
@harshalkaigaonkar 
Did you check the new elements of header under sec/client/static/logo ? A GIF is there maybe that will work and we also have CSS in it too.

**Comment by harshalkaigaonkar** [comment]
did package.json is not on the project?

**Comment by harshalkaigaonkar** [comment]
Actually development server is not starting

**Comment by tarunnsingh** [comment]
Have you seen the README which mentions the different steps to work. For you, go in the client folder and run npm start.

**Comment by tarunnsingh** [comment]
@harshalkaigaonkar can you post some ScreenShots of the error you are getting.

**Comment by beatrizsmerino** [comment]
Hi!! I can try fix this issue?
Please assign me :)

**Comment by beatrizsmerino** [comment]
![image](https://user-images.githubusercontent.com/14045148/95678118-c7e67280-0bca-11eb-81ab-35a266e35430.png)
![image](https://user-images.githubusercontent.com/14045148/95677732-d717f100-0bc7-11eb-80f6-6ee48fa7fffe.png)

I understand that the problem may be this:
The text that accompanies the type logo is too large and overlaps with the other elements. I advise leaving only the logo to make it a little smaller

![image](https://user-images.githubusercontent.com/14045148/95677981-afc22380-0bc9-11eb-9e8e-70e796590b21.png)
![image](https://user-images.githubusercontent.com/14045148/95678024-f6b01900-0bc9-11eb-8af3-d5b803509328.png)
![image](https://user-images.githubusercontent.com/14045148/95678086-85bd3100-0bca-11eb-87e8-e81b9a7fb63a.png)

**Comment by beatrizsmerino** [comment]
![image](https://user-images.githubusercontent.com/14045148/95677981-afc22380-0bc9-11eb-9e8e-70e796590b21.png)
![image](https://user-images.githubusercontent.com/14045148/95678024-f6b01900-0bc9-11eb-8af3-d5b803509328.png)

**Comment by tarunnsingh** [comment]
Hey! @beatrizsmerino that's exactly the solution.

**Comment by beatrizsmerino** [comment]
Hey! it is fixed, tell me if all it is ok :)
