### ISSUE TITLE
Added Cors to v1-Deployment

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#62]
Image fetching is blocked by client due to cors policy

**Comment by imabp** [comment]
PR #61  fixes this

**Comment by tarunnsingh** [comment]
@imabp 
This dosen't work, was trying it locally also. Merged #61 as I too had the same setup locally.
The way to fix this is to make axios/fetch requests from client. Actually the requests are not following the cors-anywhere path. That needs to be fixed and we are done. Moreover the links in the blogs-posts (which are actually inside markdown files) also need to be changed manually :confused: as of now.

We need to set up a better architecture. 
We have good amount of content coming up.
