### ISSUE TITLE
Cleaning the codebase.

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#68]
# Current State looks non modular 
![image](https://user-images.githubusercontent.com/53480076/95517022-d6bc0200-09dd-11eb-9f27-7f1833200989.png)

# After Cleaning ( PR #67 )

![image](https://user-images.githubusercontent.com/53480076/95517114-0408b000-09de-11eb-9dc0-2f275ba04a7b.png)

**Comment by imabp** [comment]
@tarunnsingh I have finally cleaned the codebase and its working fine. On deployment. #67 

Hope its fine. ? .😊😊

**Comment by tarunnsingh** [comment]
That was much required. ThankS!
