### ISSUE TITLE
Adding Contributors in Sidebar.

### ISSUE THREAD

**Issue by imabp** [alexa-dev-hub/alexa-community-jaipur#7]
## Adding contributors section in sidebar using GitHub API.

![image](https://user-images.githubusercontent.com/53480076/91127889-cb7a7480-e6c4-11ea-8b51-2da05e5c0d7e.png)

**Comment by tarunnsingh** [comment]
@imabp Are you working on this?

**Comment by imabp** [comment]
Yes I am planning to work on it.

**Comment by imabp** [comment]
Can you provide me with, some keys so that I can set things up . I am facing this error on running the server:

![image](https://user-images.githubusercontent.com/53480076/91142463-6e83bc00-e6ce-11ea-9ccf-c3ccdd2b4b56.png)

**Comment by tarunnsingh** [comment]
The keys are being used on the production server. Here you can use MONGO local URL or create your own MONGO URL via Mongo Cloud.
On Mongo DB Cloud connect your cluster to an application. A sample URI:  
```mongodb+srv://<username>:<password>@ecomerce-website.qfwmi.mongodb.net/<dbname>?retryWrites=true&w=majority```

![SS](https://user-images.githubusercontent.com/31896659/91144850-354d4b00-e6d2-11ea-9a25-fcd1799876d0.jpg)

**I will add this in the Instructions part.**

**Comment by tarunnsingh** [comment]
Added in [README](https://github.com/alexa-dev-hub/alexa-community-jaipur/commit/033ce88c9717663085f7826f5b1bc37e74493d2e).

**Comment by imabp** [comment]
@tarunnsingh I have added the contributors section and tested it too, its working fine. 
**Update: I have also restricted the BOT entry in contributors section** 
## Please review #12 
![image](https://user-images.githubusercontent.com/53480076/92638164-81fe6c00-f2f7-11ea-9683-4d03f9234a92.png)

**Comment by tarunnsingh** [comment]
Merged your PR #12 

Closing now.

**Comment by tarunnsingh** [comment]
Just noticed that on clicking the usernames of contributors, the api json opens up. Slight change in the URL is required.

**Comment by imabp** [comment]
> Yaa I also noticed now oppsie 🙊🙊... 😅😅
> Actually just need to replace the href  part line 
> `<a href=`https://github.com/${contributor.login}`>`
> 

@tarunnsingh are you working on it ?

**Comment by tarunnsingh** [comment]
That's done Now, with the latest commit to master.
