### ISSUE TITLE
Add License to the repository

### ISSUE THREAD

**Issue by sumanthst24** [alexa-dev-hub/alexa-community-jaipur#8]

**Comment by sumanthst24** [comment]
I am thinking to add MIT License
Are there any suggestions regarding?

**Comment by tarunnsingh** [comment]
MIT license is suitable, go for it.

**Comment by sumanthst24** [comment]
Okay sure 
I'll also update the readme file with the license info as well

**Comment by tarunnsingh** [comment]
Sure

**Comment by sumanthst24** [comment]
https://github.com/alexa-dev-hub/alexa-community-jaipur/pull/10
created a PR

**Comment by sumanthst24** [comment]
As the PR is merged I am closing this issue
